version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g aws-cdk
      - npm install
  pre_build:
    commands:
      - echo Synthesizing the CDK app...
      - npx cdk synth
  build:
    commands:
      - echo Running all tests...
      - npm run alltests
  post_build:
    commands:
      - echo Deploying all stacks...
      - npx cdk deploy --all --require-approval never

artifacts:
  files:
    - '**/*'