version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install

  pre_build:
    commands:
      - echo Synthesizing the CDK app...
      - npx cdk synth

  build:
    commands:
      - echo Running all tests...
      - npm run alltests
      - echo Synthesizing the CDK app again...
      - npx cdk synth
      - echo Deploying all stacks...
      - npx cdk deploy --all --require-approval never