version: 0.2

phases:
  install:
    commands:
      - nvm install node # Installs the latest version of Node.js
      - nvm use node
      - npm install
  build:
    commands:
      - npm run build
      - cdk synth
  post_build:
    commands:
      - cdk deploy --require-approval never