version: 0.2

phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - npm run build
  build:
    commands:
      - npx cdk synth
  post_build:
    commands:
      - npx cdk deploy --all --require-approval never

artifacts:
  files:
    - cdk.out/**
  base-directory: cdk.out
