version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.11.0 # Example: Specify a different Node.js version if 20.11.0 is not directly supported
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - cdk synth
  post_build:
    commands:
      - cdk deploy --require-approval never