version: 0.2

phases:
  install:
    commands:
      # Ensure using the latest Node.js version (18)
      - nvm install 18
      - nvm use 18
      # Install dependencies
      - echo Installing dependencies...
      - npm install

  pre_build:
    commands:
      # Synthesize CloudFormation templates from the CDK app
      - echo Synthesizing the CDK app...
      - npx cdk synth

  build:
    commands:
      # Run all tests
      - echo Running all tests...
      - npm run alltests

  post_build:
    commands:
      # Deploy the application using CDK
      - echo Deploying the application...
      - npx cdk deploy --all

artifacts:
  files:
    # Specify files or directories to include as build artifacts
    - cdk.out/**