version: 0.2

phases:
  install:
    commands:
      - echo Installing source NPM dependencies...
      - npm ci
  pre_build:
    commands:
      - echo Running pre-build steps...
  build:
    commands:
      - echo Synthesizing the CDK app...
      - npx cdk synth
      - echo Running unit tests...
      - npm test
artifacts:
  files:
    - cdk-cicd/cdk.out/**
  base-directory: .