version: 0.2

phases:
  install:
    commands:
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
      - . ~/.nvm/nvm.sh
      - nvm install node # Installs the latest version of Node.js
      - nvm use node
      - npm install
  build:
    commands:
      - npm run build
      - cdk synth
  post_build:
    commands:
      - cdk deploy --require-approval never